### ISSUE TITLE
this works?

### ISSUE THREAD

**Issue by itsOwen** [Borisizdabezt/exitlag-hwid-spoofer#1]
do you have a video that shows it works?

**Comment by Borisizdabezt** [comment]
yes it does 
video? i will do it later (tomorrow)

**Comment by toblerone04** [comment]
why is it hard to download it keeps stopping in 248kb and the download speed is too slow

**Comment by Borisizdabezt** [comment]
lul github server not mine

**Comment by toblerone04** [comment]
i get this error
![unknown_2021 11 16-20 08](https://user-images.githubusercontent.com/94446967/141982808-7e98614b-d814-4177-af59-87465c01fed8.png)
![unknown_2021 11 16-20 08_1](https://user-images.githubusercontent.com/94446967/141982832-0e5d2bb8-4711-4f5d-b9ca-152f84ae43dc.png)
![unknown_2021 11 16-20 08_2](https://user-images.githubusercontent.com/94446967/141982837-32556724-fc78-4278-aeff-df43e7dbb244.png)
![unknown_2021 11 16-20 08_3](https://user-images.githubusercontent.com/94446967/141982842-448c8bc0-6e72-49ac-93a5-c6ecf48c2353.png)

**Comment by toblerone04** [comment]
then when i try to put all the dll files i got this error
![unknown_2021 11 16-20 14](https://user-images.githubusercontent.com/94446967/141983639-d6de5a14-301f-4b7e-9af4-38a28c643809.png)

**Comment by Borisizdabezt** [comment]
lol install wdk bro (windows driver kit)

**Comment by toblerone04** [comment]
> lol install wdk bro (windows driver kit)

ok brother ill try :( sorry im new to this i just want to play with out packet loss thats why im trying my best

**Comment by Borisizdabezt** [comment]
tomorrow i will upload video lul (Vietnamese internet sucks)
