### ISSUE TITLE
not work anymore

### ISSUE THREAD

**Issue by specurial** [Borisizdabezt/exitlag-hwid-spoofer#10]
hi
exitlag refuse to connect at all after optimization end,
none of them cannot connect to exitlag servers (chrome,discord,games, ...)
they fixed this trick in another way :(

**Comment by Borisizdabezt** [comment]
#3

**Comment by Borisizdabezt** [comment]
sorry for late reply (i forgot my github password)

**Comment by specurial** [comment]
its okay mate and everything works fine 🍻
