### ISSUE TITLE
Unable to load vulnerable driver

### ISSUE THREAD

**Issue by Sirone-10** [Borisizdabezt/exitlag-hwid-spoofer#11]
![image](https://user-images.githubusercontent.com/76997900/157908412-30ee7e0a-9b7c-4862-ab2b-c27a5f207db4.png)
Hey! I have a problem with Exitlag Trial Reset
[!] Unable to load vulnerable driver, NTSTATUS (0xC0000022)

**Comment by Borisizdabezt** [comment]
you need to disable your anti-cheat (ESEA, FaceIT AC, EAC,...) and antivirus (Kaspersky, Avast,...)

**Comment by gosu821** [comment]
ông mới update 27 ngày trước ý
ông giải thích dùng ntn đi

**Comment by Borisizdabezt** [comment]
> ông mới update 27 ngày trước ý ông giải thích dùng ntn đi

mở file lên spoof rồi đăng nhập acc exitlag mới để activate xong restart máy rồi boot máy lên mở exitlag rồi chiến game thoi

**Comment by Borisizdabezt** [comment]
nhiều ông spoof xong không restart rồi ăn ban sml cứ lên bảo sao bị ban

**Comment by gosu821** [comment]
cảm ơn ô nha
Tiếp tục dự án này khi exitlag update nha
cảm ơn ô vì cộng đồng
