### ISSUE TITLE
Не работает (

### ISSUE THREAD

**Issue by CraZZyAngel** [Borisizdabezt/exitlag-hwid-spoofer#13]
![vaccine](https://user-images.githubusercontent.com/102385312/160186587-83b38333-cbc3-44c9-876a-71a4b30ccf53.png)
Лавочку прикрыли, или у меня что-то не так?

**Comment by Borisizdabezt** [comment]
:)

**Comment by Borisizdabezt** [comment]
https://github.com/Borisizdabezt/exitlag-hwid-spoofer/releases/tag/sputnik2.0
use this old one
