### ISSUE TITLE
VAC,Ban

### ISSUE THREAD

**Issue by Drakz-z** [Borisizdabezt/exitlag-hwid-spoofer#15]
Hey, my friend go banned from valorant for using this spoofer but i didn't got banned i didn't get it how does this happened anyways i want to know how do i revert this

**Comment by Borisizdabezt** [comment]
lol your friend didnt restart his pc

**Comment by Borisizdabezt** [comment]
always restart pc after using this spoofer

**Comment by Borisizdabezt** [comment]
i used this and play csgo for 9 months and i was not banned so it's your friend's fault. I cant help you guys

**Comment by Drakz-z** [comment]
ok, thanks man

**Comment by Drakz-z** [comment]
i want to know if do this again and restart will i get banned ?

**Comment by Borisizdabezt** [comment]
spoof in test mode, activate new exitlag account then restarting (after restarting, the driver will be unloaded so you wont get banned)
