### ISSUE TITLE
Valorant User Do'nt Use them

### ISSUE THREAD

**Issue by FranklinOP-IND** [Borisizdabezt/exitlag-hwid-spoofer#16]
Driver.sys Is Banble i using bypass but elay ban

**Comment by Borisizdabezt** [comment]
Vanguard will block the driver when you run spoofer so you need to disable (you cant play if you disable Vanguard)

**Comment by Borisizdabezt** [comment]
and you were using bypass? (wtf lol)

**Comment by FranklinOP-IND** [comment]
> and you were using bypass? (wtf lol)

Yup Not Ban 2d day aftr ban Using this driver XD

**Comment by Borisizdabezt** [comment]
> > and you were using bypass? (wtf lol)
> 
> Yup Not Ban 2d day aftr ban Using this driver XD

xD that reason why i wrote "you will get banned" when you choose [2]

**Comment by Borisizdabezt** [comment]
duplicate #14

**Comment by Borisizdabezt** [comment]
#15
