### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Eashwar-NN** [Borisizdabezt/exitlag-hwid-spoofer#17]
Hi, been using it for a while and used to work fine. I'm currently having issues using it now. My trial wont get credited.

**Comment by Eashwar-NN** [comment]
I've ran in both test mode as well as w/o test mode, nothing seems to work.

**Comment by Borisizdabezt** [comment]
step 1: you create a new exitlag account
step 2: sign out exitlag
step 3: boot into test mode through launchthis.exe
step 4: after booting into test mode, open launchthis.exe then choose 1
step 5: open exitlag and login the new exitlag account
step 6: restart your pc
step 7: open exitlag and enjoy (you can run exitlag without spoofer after step 6)

**Comment by Eashwar-NN** [comment]
how do you boot into test mode with launchthis? it only asks me if im in test mode or not

**Comment by Borisizdabezt** [comment]
choose N to boot into test mode
