### ISSUE TITLE
Vmware

### ISSUE THREAD

**Issue by Drakz-z** [Borisizdabezt/exitlag-hwid-spoofer#24]
if i use it on vmware will i be safe ?

**Comment by Borisizdabezt** [comment]
idk, test it

**Comment by Drakz-z** [comment]
i am scared lmao , my friend got banned from valorant even after restarting so i don't wanna try and get banned

**Comment by Drakz-z** [comment]
Well i tried , and i am in test mode , i will spoof and login , then disable test mode and restart then try i hope i wont get banned ' i wont use my main tho '

**Comment by intox-ai** [comment]
> Well i tried , and i am in test mode , i will spoof and login , then disable test mode and restart then try i hope i wont get banned ' i wont use my main tho '

did you get banned or what so ever? ar you sure ur friend wasn't just cheating?

**Comment by Drakz-z** [comment]
he got banned and he wasn't cheating at all, i also got banned but i wasn't using my account just to make sure i wont get banned , i just bought a sub and i stopped using this program

**Comment by Borisizdabezt** [comment]
vmware: nope

**Comment by amo81irkh** [comment]
Hello friends, I am new here. What programming language do you use?

**Comment by Drakz-z** [comment]
This issue is now closed (VMware is not supported)
