### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Aryoper** [Borisizdabezt/exitlag-hwid-spoofer#26]
Hi,
What's this error?! What can I do?

![Screenshot (1)](https://user-images.githubusercontent.com/117476749/200047142-9533c1f0-51ef-4f3a-b64e-513483d83a32.jpeg)

**Comment by MotorolaRAZR** [comment]
deactivate ur antivirus and boot into test mode

**Comment by FobNewPLayyer** [comment]
doesnt work even in test mode
