### ISSUE TITLE
does this get you ban?

### ISSUE THREAD

**Issue by ZeroTwoSimp420** [Borisizdabezt/exitlag-hwid-spoofer#4]
will i get ban on my games?

**Comment by Borisizdabezt** [comment]
no

**Comment by Borisizdabezt** [comment]
+anti cheat bypass (+100% power)

**Comment by YMY1666527646** [comment]
Is it applicable to apex?

**Comment by Borisizdabezt** [comment]
> Is it applicable to apex?

no

**Comment by Borisizdabezt** [comment]
EAC sucks

**Comment by wizard460** [comment]
So can you get banned in fortnite?

**Comment by Borisizdabezt** [comment]
i didnt test with fortnite idk

**Comment by Borisizdabezt** [comment]
fortnite uses eac and it sucks

**Comment by YMY1666527646** [comment]
Sorry to ask, isn't this hwid spoofer?

**Comment by Borisizdabezt** [comment]
it is hwid spoofer

**Comment by Simongxontic** [comment]
> i didnt test with fortnite idk

did u try it yet?

**Comment by Borisizdabezt** [comment]
#5
