### ISSUE TITLE
Can u get banned if u use this on fortnite?

### ISSUE THREAD

**Issue by Simongxontic** [Borisizdabezt/exitlag-hwid-spoofer#5]

**Comment by Borisizdabezt** [comment]
yea :( EAC sucks

**Comment by Borisizdabezt** [comment]
u will get ban if u use it

**Comment by Simongxontic** [comment]
> u will get ban if u use it

Why??

**Comment by ghost** [comment]
> > u will get ban if u use it
> 
> Why??

Definitely dont do it if you play fortnite, I just received a ban and got my account banned for 24 hours along with the warning.  😭

**Comment by Borisizdabezt** [comment]
use it with EAC bypass bro
or load it before EAC starts

**Comment by Borisizdabezt** [comment]
https://github.com/thesecretclub/CVEAC-2020

**Comment by Borisizdabezt** [comment]
my computer cannot compile it (windowskerneldriver 1.0 sucks) so do it yourself :)

**Comment by Borisizdabezt** [comment]
or this https://github.com/Schnocker/EAC_dbp

**Comment by Borisizdabezt** [comment]
or use efi-memory to load driver before EAC or some anti-cheats open
https://github.com/SamuelTulach/efi-memory

**Comment by Simongxontic** [comment]
> or use efi-memory to load driver before EAC or some anti-cheats open https://github.com/SamuelTulach/efi-memory

If its posibble can u make an new exitlag craked and but not bannible for fortnite, thank u

**Comment by Borisizdabezt** [comment]
> > or use efi-memory to load driver before EAC or some anti-cheats open https://github.com/SamuelTulach/efi-memory
> 
> If its posibble can u make an new exitlag craked and but not bannible for fortnite, thank u

no way to do it, because exitlag will check our hwid. If we want to change hwid, we will need to spoof our hwid or reinstall windows

**Comment by Simongxontic** [comment]
Dang i really want to do this but im gonna get banned from fortnite

**Comment by Borisizdabezt** [comment]
huh i found a new way again lul :)
boot into safe mode with network (or test mode), run spoofer , activate your exitlag account, use for 2-3 minutes then restart boot into normal windows and it worked (remember to check "Keep me connected" when run spoofer in test mode)

**Comment by Simongxontic** [comment]
> huh i found a new way again lul :) boot into safe mode with network (or test mode), run spoofer , activate your exitlag account, use for 2-3 minutes then restart boot into normal windows and it worked (remember to check "Keep me connected" when run spoofer in test mode)

So ur sure i wont get banned? Have u tryed this on fotnite?

**Comment by Borisizdabezt** [comment]
no i didnt but i can sure if u boot into test mode, run spoofer and activate your account then get out test mode and restart. It will unload driver and u wont be got banned

**Comment by Borisizdabezt** [comment]
tested with FaceIT AC, Vanguard (need to use Vanguard toggler) but didnt test with EAC xD

**Comment by Borisizdabezt** [comment]
i dont know why it worked when after restarting :))

**Comment by ghost** [comment]
Okay, Im going to try that. in the end im already banned, I cant lose anything lol. btw, thanks for supporting this. 😁
