### ISSUE TITLE
make an issue here, i will help you

### ISSUE THREAD

**Issue by Borisizdabezt** [Borisizdabezt/exitlag-hwid-spoofer#6]

**Comment by specurial** [comment]
<3

**Comment by lilithecutn** [comment]
not working bro, any fix?

**Comment by BenJatsu** [comment]
IS it virus?

**Comment by MilkyWheat101** [comment]
Wich file should I download, hotfix or source code? and how do I spoof exit lag

**Comment by Borisizdabezt** [comment]
> Wich file should I download, hotfix or source code? and how do I spoof exit lag

hotfix
