### ISSUE TITLE
no working

### ISSUE THREAD

**Issue by lilithecutn** [Borisizdabezt/exitlag-hwid-spoofer#7]
not work bro, any fix?

**Comment by Borisizdabezt** [comment]
you need to turn off antivirus and anticheat first then use spoofer

**Comment by fernandiee** [comment]
it doesn't work for me either, i did every step, twice and it didn't work. I also did it on another computer and it didn't work. I've been using gatolouco's script and it's been working until the last update, which patched it.

But yeah, gatolouco's stopped working on the script so I have no idea how to fix it, and this didn't work either.

**Comment by Borisizdabezt** [comment]
lul

**Comment by Borisizdabezt** [comment]
did you turn off your anti-cheat? If you turned off anti-cheat but it's not working, try booting into test mode and run vaccine.exe again

**Comment by fernandiee** [comment]
> did you turn off your anti-cheat? If you turned off anti-cheat but it's not working, try booting into test mode and run vaccine.exe again

i did, and with the new release I press 1 to go into test mode and then I press 2 when the computer restarts, am I doing something wrong?

**Comment by Borisizdabezt** [comment]
which game are you playing? @fernandiee

**Comment by Borisizdabezt** [comment]
> > did you turn off your anti-cheat? If you turned off anti-cheat but it's not working, try booting into test mode and run vaccine.exe again
> 
> i did, and with the new release I press 1 to go into test mode and then I press 2 when the computer restarts, am I doing something wrong?

option 1 is no longer boot into test mode, it will spoof then restarting, option 2 is spoofing without restarting.
I will see it again

**Comment by fernandiee** [comment]
> > > did you turn off your anti-cheat? If you turned off anti-cheat but it's not working, try booting into test mode and run vaccine.exe again
> > 
> > 
> > i did, and with the new release I press 1 to go into test mode and then I press 2 when the computer restarts, am I doing something wrong?
> 
> option 1 is no longer boot into test mode, it will spoof then restarting, option 2 is spoofing without restarting. I will see it again

Now it works, with the new fix that you uploaded. I tried it twice and it works perfectly. 

What I did was run vaccine.exe as Administrator, then press 1 and select ExitLag's .exe file, when the computer restarts I created a new account, run vaccine.exe as Administrator and choose 2.

After that, I login into my new account and I have the 3 days of trial. I did this twice on my laptop (i recommend doing this on another computer that's not your main to avoid ban altogether) and it worked twice. Thanks Boris.

**Comment by fernandiee** [comment]
> > > > did you turn off your anti-cheat? If you turned off anti-cheat but it's not working, try booting into test mode and run vaccine.exe again
> > > 
> > > 
> > > i did, and with the new release I press 1 to go into test mode and then I press 2 when the computer restarts, am I doing something wrong?
> > 
> > 
> > option 1 is no longer boot into test mode, it will spoof then restarting, option 2 is spoofing without restarting. I will see it again
> 
> Now it works, with the new fix that you uploaded. I tried it twice and it works perfectly.
> 
> What I did was run vaccine.exe as Administrator, then press 1 and select ExitLag's .exe file, when the computer restarts I create a new account, run vaccine.exe as Administrator and choose 2.
> 
> After that, I login into my new account and I have the 3 days of trial. I did this twice on my laptop (i recommend doing this on another computer that's not your main to avoid ban altogether) and it worked twice. Thanks Boris.

I just did it a third time but without running vaccine.exe after the windows restart and it doesn't work. So afterwards I ran vaccine.exe and chose option 2, logged in again and it worked, so it seems that it is essential to make a new account, run vaccine.exe as Administrator, choose option 1, after the computer restarts, run vaccine.exe as Administrator again and choose option 2, log in and it'll give you 3 days of trial. I did this 3 times on my laptop and it worked, so props to Boris.

**Comment by Borisizdabezt** [comment]
> > > > > did you turn off your anti-cheat? If you turned off anti-cheat but it's not working, try booting into test mode and run vaccine.exe again
> > > > 
> > > > 
> > > > i did, and with the new release I press 1 to go into test mode and then I press 2 when the computer restarts, am I doing something wrong?
> > > 
> > > 
> > > option 1 is no longer boot into test mode, it will spoof then restarting, option 2 is spoofing without restarting. I will see it again
> > 
> > 
> > Now it works, with the new fix that you uploaded. I tried it twice and it works perfectly.
> > What I did was run vaccine.exe as Administrator, then press 1 and select ExitLag's .exe file, when the computer restarts I create a new account, run vaccine.exe as Administrator and choose 2.
> > After that, I login into my new account and I have the 3 days of trial. I did this twice on my laptop (i recommend doing this on another computer that's not your main to avoid ban altogether) and it worked twice. Thanks Boris.
> 
> I just did it a third time but without running vaccine.exe after the windows restart and it doesn't work. So afterwards I ran vaccine.exe and chose option 2, logged in again and it worked, so it seems that it is essential to make a new account, run vaccine.exe as Administrator, choose option 1, after the computer restarts, run vaccine.exe as Administrator again and choose option 2, log in and it'll give you 3 days of trial. I did this 3 times on my laptop and it worked, so props to Boris.

hmmm option 1 is worked for me but it didnt work for you guys :( so sad

**Comment by fernandiee** [comment]
@Borisizdabezt so do you only run vaccine.exe as admin, select the exitlag.exe, choose option 1 and when the computer restarts you make an account and it'll have 3 days of trial? and just repeat the process once is over?

**Comment by Borisizdabezt** [comment]
> @Borisizdabezt so do you only run vaccine.exe as admin, select the exitlag.exe, choose option 1 and when the computer restarts you make an account and it'll have 3 days of trial? and just repeat the process once is over?

create a new account, run vaccine.exe as admin, choose option 1, select the exitlag.exe, sign in your account after spoofing then restart
